version: '3'

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:12.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    logging:
      driver: none

  django:
    build:
      context: .
      dockerfile: ./dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: football_schedule_maker
    depends_on:
      - postgres
